AWS_REGION: ap-northeast-2
STAGE: dev
DEPLOYMENT_BUCKET: allive-serverless-deployment
CORS_ORIGIN: '*'
DOMAINS:
  prod: vmapi.footballpie.io
  dev: dev-vmapi.footballpie.io
DB_CONFIG:
  dev:
    DB_TYPE: mysql
    DB_HOST: localhost
    DB_PORT: 3306
    DB_USER: vanillameta
    DB_PASSWORD: pw
    DB_NAME: vanillameta
  prod:
    DB_TYPE: mysql
    DB_HOST: localhost
    DB_PORT: 3306
    DB_USER: vanillameta
    DB_PASSWORD: pw
    DB_NAME: vanillameta
