AWS_REGION: ap-northeast-2
STAGE: dev
DEPLOYMENT_BUCKET: vanilla-serverless-deployment
CORS_ORIGIN: 'https://vanillameta.vanillabrain.com, http://localhost:3000'
DOMAINS:
  prod: api.vanillameta.net
  dev: api-dev.vanillameta.net
DB_CONFIG:
  dev:
    DB_TYPE: mysql
    DB_HOST: localhost
    DB_PORT: 3306
    DB_USER: vanillameta
    DB_PASSWORD: pw
    DB_NAME: vanillameta
  prod:
    DB_TYPE: mysql
    DB_HOST: localhost
    DB_PORT: 3306
    DB_USER: vanillameta
    DB_PASSWORD: pw
    DB_NAME: vanillameta
