#FROM mysql:5.7
#
##ENV DEBIAN_FRONTEND noninteractive
#
#RUN apt-get update
##RUN echo "mysql-server mysql-server/root_password password" | debconf-set-selections
##RUN echo "mysql-server mysql-server/root_password_again password" | debconf-set-selections
##RUN apt-get install -y mysql-server
#
#ADD ./mysql-init-files /docker-entrypoint-initdb.d
#
#EXPOSE 3306
#
#CMD ['mysqld']
#FROM mysql:5.7
#
#ADD ./mysql-init-files /docker-entrypoint-initdb.d
#
#EXPOSE 3306
#
#CMD ["mysqld"]
FROM ubuntu:18.04



RUN apt-get -qq update
RUN apt-get -qq upgrade --yes
RUN apt-get -qq install curl --yes
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get -qq install nodejs --yes

RUN apt-get install chromium-browser --yes

RUN useradd -ms /bin/bash frog
USER frog
WORKDIR /home/frog

COPY package*.json ./

RUN npm install

COPY . .
COPY tsconfig.json .
COPY tsconfig.build.json .

RUN chmod *x init.sh
ENTRYPOINT ./init.sh

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:prod"]