export const WIDGET_TYPE = {
  CHART_LINE: 'CHART_LINE',
  CHART_AREA: 'CHART_AREA',
  CHART_BAR: 'CHART_BAR',
  CHART_COLUMN: 'CHART_COLUMN',
  CHART_PIE: 'CHART_PIE',
  CHART_DONUT: 'CHART_DONUT',
  CHART_NIGHTINGALE: 'CHART_NIGHTINGALE',
};
