service: vanillameta-frontend

frameworkVersion: '2 || 3'

package:
  patterns:
  - '!*'
  - '!*/**'
  - node_modules/**
  - '!node_modules/aws-sdk'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${file(./config.serverless.yml):AWS_REGION}
  deploymentBucket: ${file(./config.serverless.yml):DEPLOYMENT_BUCKET}
  environment:

plugins:
  - serverless-frontend-plugin

custom:
  STAGE: ${self:provider.stage}
  FRONT_WEB_BUCKET: ${file(./config.serverless.yml):FRONT_WEB_BUCKET}
  FRONT_WEB_DOMAIN: ${file(./config.serverless.yml):FRONT_WEB_DOMAIN}
  RUN_CMD: ${file(./config.serverless.yml):RUN_CMD}
  serverless-frontend-plugin:
    distDir: build
    build:
      cwdDir: frontend-web
      command:
        - npm
        - run
        - ${self:custom.RUN_CMD.${self:provider.stage}}
#      env:
#        NODE_ENV: dev
#        REACT_APP_MODE: dev
#        REACT_APP_API_URL: ${file(./config.serverless.yml):BACKEND_API_DOMAIN}
#    offline:
#      cwdDir: frontend
#      command:
#        - yarn
#        - serve
#      env:
#        NODE_ENV: development
#        VUE_APP_API_BASE_URL: http://localhost:7680
    bucket:
      name: ${self:custom.FRONT_WEB_BUCKET.${self:provider.stage}}
    distribution:
      dnsName: ${self:custom.FRONT_WEB_DOMAIN.${self:provider.stage}}
      acmCertificateArn: ${file(./config.serverless.yml):ACM_CERTIFICATE_ARN}
      hostedZoneName: ${file(./config.serverless.yml):HOSTED_ZONE}